src/core/urls.py
from django.conf.urls import url, include

from . import views, grievance


urlpatterns = [
    url(r'^$', grievance.dashboard, name='dashboard_home'),
#     url(r'^register', views.register, name='register'),
    url(r'^grievance/add', grievance.add, name='add'),
    url(r'^grievance/all', grievance.allIssues, name='all'),
    url(r'^grievance/view/(?P<grievance_id>[0-9]+)', grievance.view, name='view'),
    url(r'^grievance/review/(?P<grievance_id>[0-9]+)', grievance.review, name='review'),
    url(r'^grievance/track/(?P<grievance_id>[0-9]+)', grievance.track, name='track'),
    url(r'^department/all', grievance.departments, name='dept_all'),
    url(r'^department/save', grievance.saveDepartment, name='dept_save'),
    url(r'^dashboard', grievance.dashboard, name='dashboard_main'),

]

src/pgs/urls.py
from django.conf.urls import include, url
from rest_framework import routers
from core  import grievance
from django.contrib import admin


router = routers.DefaultRouter()
router.register(r'^issues', grievance.IssueViewSet)

urlpatterns = [
    url(r'^', include('core.urls', namespace='core')),
    url(r'^', include('accounts.urls', namespace='accounts')),
    url(r'^api/', include(router.urls)),
    url(r'^auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^admin/', include(admin.site.urls)),
]

src/core/models.py
from django.db import models
from django.conf import settings
from jsonfield import JSONField


class Department(models.Model):
    dept_id = models.AutoField(primary_key=True)
    name    = models.CharField(max_length=40)
    description = models.CharField(max_length=255, blank=True)

    def __str__(self):
        return '[Name: ' + self.name + ', Description: ' + self.description +']'

class IssueStatus(models.Model):
    status = models.CharField(max_length=40)

class Issue(models.Model):

    class Meta:
        permissions = (
            ('review_issue', 'Can change the status of issue'),
        )

    issue_id    = models.AutoField(primary_key=True)
    status  = models.ForeignKey(IssueStatus)
    title   = models.CharField(max_length=256)
    content = models.TextField(max_length=1024)
    pic     = models.CharField(max_length=80, blank=True)
    latitude    = models.CharField(max_length=20, blank=True)
    longitude   = models.CharField(max_length=20, blank=True)
    geo_address     = JSONField(blank=True)
    twitter_handle  = models.CharField(max_length=20, blank=True)
    tweet   = JSONField(blank=True)
    category    = models.ForeignKey(Department, null=True)

    """
    TODO Make user compulsory - once user models are generated from tweets
    """
    user    = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True)

    def __str__(self):
        return '[Title: '+ self.title + ', Content: ' + self.content + ', User: ' + self.user.username + ']'

class Discussion(models.Model):
    issue   = models.ForeignKey(Issue)
    message = models.CharField(max_length=1024)

src/core/forms.py
from django import forms
from django.forms import ModelForm
from .models import Issue, Department


class GrievanceForm(ModelForm):
    #image   = forms.FileField()

    class Meta:
        model = Issue

        fields = ['title', 'content', 'latitude', 'longitude']
        widgets = {
            'latitude': forms.HiddenInput(attrs={'id': 'latitude'}),
            'longitude': forms.HiddenInput(attrs={'id': 'longitude'}),
        }
    def __init__(self, *args, **kwargs):
        super(GrievanceForm, self).__init__(*args, **kwargs)
        self.fields['latitude'].required = False
        self.fields['longitude'].required = False

class DepartmentForm(ModelForm):

    class Meta:
        model = Department

        fields = ['name', 'description']
        widgets = {
            'name': forms.TextInput(attrs={'id': 'dept_name'}),
            'description': forms.Textarea(attrs={'id': 'dept_description'})
        }

src/core/views.py
from django.shortcuts import render
from django.contrib.auth.models import User

import traceback

# def index(request):
#     all_roles = UserRole.objects.all()
#     role_options = []
#     for role in all_roles:
#         role_options.append({'id': role.id, 'role_name': role.role_name})
#     return render(request, 'core/index.html', {'role_options': role_options})
# 
# 
# 
# def register(request):
#     if request.method == 'POST':
#         form = RegistrationForm(request.POST)
#         if form.is_valid():
#             try:
#                 new_user = form.save(commit=False)
#                 new_user.save()
#             except Exception as e:
#                 context = {
#                         'alert_type': 'alert-danger',
#                         'content': 'Registration failed!! Unable to save.'
#                     }
#                 print(type(new_user).__name__)
#                 traceback.print_exc()
#                 return render(request, 'core/message.html', context)
#             context = {
#                     'alert_type': 'alert-success',
#                     'content': 'Registration successful!!'
#                 }
#             return render(request, 'core/message.html', context)
#     else:
#         form = RegistrationForm()
# 
#     return render(request, 'core/register.html', {'form': form})

# def register(request):
#     if request.method != 'POST':
#         context = {
#                     'alert_type': 'alert-danger',
#                     'content': 'Invalid request!!'
#                 }
#         return render(request, 'core/message.html', context)
#     user_name = request.POST['username']
#     user_password = request.POST['password']
#     user_re_password = request.POST['re-password']
#     user_role = request.POST['user_role']
#
#     if(user_password == user_re_password):
#         new_user = User(username = user_name, password = user_password)
#         try:
#             new_user.save()
#             print('New_user: '+ str(new_user))
#             role_obj = UserRole.objects.filter(id=user_role).get()
#             print('User role: ' + type(role_obj).__name__)
#             profile = UserProfile(user = new_user, role = role_obj)
#             profile.save()
#         except Exception as e:
#             print(e)
#             new_user.delete()
#             context = {
#                         'alert_type': 'alert-danger',
#                         'content': 'Registration failed!!'
#                     }
#             return render(request, 'core/message.html', context)
#
#         context = {
#                     'alert_type': 'alert-success',
#                     'content': 'Registration successful!!'
#                 }
#         return render(request, 'core/message.html', context)
#
#     context = {
#                 'alert_type': 'alert-warning',
#                 'content': 'Registration failed!! Passwords did not match.'
#             }
#     return render(request, 'core/message.html', context)

src/core/templates/grievance/add.html
{% extends "layouts/default.html" %}
{% load staticfiles %}

{% block content %}
    <div >
        <form action="" method="POST" >
            <fieldset>
                <legend>Add new grievance</legend>
                {% csrf_token %}
                {{ form.non_field_errors }}
                <div class="form-group">
                    {{ form.title.errors }}
                    <label for="{{ form.title.id_for_label }}">Title:</label>
                    {{ form.title }}
                </div>
                <div class="form-group">
                    {{ form.content.errors }}
                    <label for="{{ form.content.id_for_label }}">Your complaint:</label>
                    {{ form.content }}
                </div>
                <div class="form-group">
                    <strong>Pick the location</strong>
                    <div id="pickerMap" style="width: 800px; height: 400px;"></div>
	                {{ form.latitude  }}
	                {{ form.longitude }}
                <!--
                    <button id="mylocation" class="btn btn-default" type="button" title="My location">
                        <span class="glyphicon glyphicon-screenshot"></span>
                    </button>
                -->
                </div>
                <input class="btn btn-primary" type="submit" value="Submit" />
            </fieldset>
        </form>
    </div>
{% endblock %}

{% block scriptsAppend %}
    <script type="text/javascript" src='http://maps.google.com/maps/api/js?sensor=false&libraries=places'></script>
    <script type="text/javascript" src="{% static 'js/locationpicker.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/geo.js' %}"></script>
{% endblock %}

src/core/templates/grievance/all.html
{% extends "layouts/default.html" %}
{% load staticfiles %}

{% block content %}
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Id</th>
                <th>Issue</th>
                <th>Status</th>
                <th>Category</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for issue in all_issues %}
            <tr>
                <td><a href="{% url 'core:view' issue.issue_id %}">{{issue.issue_id}}</a></td>
                <td><a href="{% url 'core:view' issue.issue_id %}"><strong>{{issue.title}}</strong><br></a> {{ issue.content }}</td>
                <td>{{issue.status.status}}</td>
                <td>
                    {% if issue.category %}
                    {{ issue.category.name }}
                    {% else %}
                    Uncategorized
                    {% endif %}
                </td>
                {% if user.role.roleid == 2 %}
                <td><a href="{% url 'core:review' issue.issue_id %}">Review</a></td>
                {% endif %}
                <td><a href="{% url 'core:track' issue.issue_id %}">Track</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <nav>
       	<ul class="pager">
        	<span class="step-links">
        	{% if all_issues.has_previous %}
        		<li class="previous">
        			<a href="?page={{all_issues.previous_page_number}}">
        			<span aira-hidden="true">&larr;</span>Previous
        			</a>
       			</li>
       		{% else %}
       			<li class="previous disabled">
        			<a href="">
        			<span aira-hidden="true">&larr;</span>Previous
        			</a>
       			</li>
        	{% endif %}
        		<li class="current">
        			Page {{ all_issues.number }} of {{ all_issues.paginator.num_pages }}
        		</li>

        	{% if all_issues.has_next %}
        		<li class="next">
        			<a href="?page={{all_issues.next_page_number}}">Next
        			<span aira-hidden="true">&rarr;</span>
        			</a>
       			</li>
       		{% else %}
       			<li class="next disabled">
        			<a href="">Next
        			<span aira-hidden="true">&rarr;</span>
        			</a>
       			</li>
       		{% endif %}

			</ul>
        </nav>
{% endblock %}

src/core/templates/grievance/review.html
{% extends "layouts/default.html" %}
{% load staticfiles %}

{% block content %}
    {% if message != '' %}
    <div class="alert {{messageStatus}} alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        {{ message }}
    </div>
    {% endif %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">#{{grievance.issue_id}} {{grievance.title}}</h3>
        </div>
        <ul class="list-group">
            <li class="list-group-item">{{grievance.content}}</li>
        </ul>
        {% if grievance.geo_address %}
        <div class="panel-body">
            <div class="col-sm-3">
                <strong>Address:</strong><br>
                {% for addr in grievance.geo_address.0.address_components %}
                    {{ addr.long_name }}<br>
                {% endfor %}
            </div>
            <div class="col-sm-8">
                <div id="pickerMap" style="width: 800px; height: 300px;"></div>
            </div>
        </div>
        {% endif %}
        <ul class="list-group">
            <form class="form-inline" action="" method="post">
                <input name="issue_id" type="hidden" value="{{grievance.issue_id}}" />
                <li class="list-group-item"><strong>Status:</strong><br>
                    {% csrf_token %}
                    <select name="status_id">
                        {% for status in statuses %}
                            {% if grievance.status.id == status.id %}
                                <option value="{{status.id}}" selected="True">{{status.status}}</option>
                            {% else  %}
                                <option value="{{status.id}}" >{{status.status}}</option>
                            {% endif %}
                        {% endfor %}
                    </select>
                </li>
                <li class="list-group-item"><strong>Category:</strong><br>
                    <select name="category_id" >
                        <option value="0" selected="True">Uncategorized</option>
                        {% for department in departments %}
                            {% if grievance.category and grievance.category.dept_id == department.dept_id %}
                                <option value="{{department.dept_id}}" selected="True">{{department.name}}</option>
                            {% else %}
                                <option value="{{department.dept_id}}" >{{department.name}}</option>
                            {% endif %}
                        {% endfor %}
                    </select>
                    <button class="btn btn-primary" type="submit">Save changes</button>
                </li>
            </form>
        </ul>
    </div>
{% endblock %}

{% block scriptsAppend %}
    <script type="text/javascript" src='http://maps.google.com/maps/api/js?sensor=false&libraries=places'></script>
    <script type="text/javascript" src="{% static 'js/locationpicker.js' %}"></script>
    <script>
        $('#pickerMap').locationpicker({
            location: {latitude: {{ grievance.latitude }}, longitude: {{ grievance.longitude}} },
            radius: 50
        });
    </script>
{% endblock %}

src/core/templates/grievance/track.html
{% extends "layouts/default.html" %}
{% load staticfiles %}

{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">#{{grievance.issue_id}} {{grievance.title}}</h3>
        </div>
        <ul class="list-group">
            <li class="list-group-item">{{grievance.content}}</li>
        </ul>
        {% if grievance.geo_address %}
        <div class="panel-body">
            <div class="col-sm-3">
                <strong>Address:</strong><br>
                {% for addr in grievance.geo_address.0.address_components %}
                    {{ addr.long_name }}<br>
                {% endfor %}
            </div>
            <div class="col-sm-8">
                <div id="pickerMap" style="width: 800px; height: 300px;"></div>
            </div>
        </div>
        {% endif %}
        <ul class="list-group">
            <li class="list-group-item"><strong>Status:</strong><br>
            {% if status.id == 6 %}
            	<div class="text-danger">
	            	<span class="glyphicon glyphicon-exclamation-sign"></span>
	            	The issue has been marked as spam.
	            </div>
            {% elif status.id == 7 %}
            	<div class="text-danger">
	            	<span class="glyphicon glyphicon-time"></span>
	            	The issue has been put on hold.
	            </div>
	        {% elif status.id == 8 %}
            	<div class="text-danger">
	            	<span class="glyphicon glyphicon-warning-sign"></span>
	            	The issue cannot be resolved.
	            </div>
            {% else %}
            	<ul class="progress-indicator">
            		{% if status.id >= 1 %}
						<li class="completed"> <span class="bubble"></span> New </li>
					{% endif %}

					{% if status.id >= 2 %}
						<li class="completed"> <span class="bubble"></span>Under verification </li>
					{% else %}
						<li> <span class="bubble"></span>Under verification </li>
					{% endif %}

					{% if status.id >= 3 %}
						<li class="completed"> <span class="bubble"></span>Assigned</li>
					{% else %}
						<li> <span class="bubble"></span>Assigned</li>
					{% endif %}

					{% if status.id >= 4 %}
						<li class="completed"> <span class="bubble"></span>Under progress</li>
					{% else %}
						<li> <span class="bubble"></span>Under progress</li>
					{% endif %}

					{% if status.id == 5 %}
						<li class="completed"> <span class="bubble"></span>Resolved</li>
					{% else %}
						<li> <span class="bubble"></span>Resolved</li>
					{% endif %}
				</ul>
            {% endif %}
            </li>
        </ul>
    </div>
{% endblock %}


{% block scriptsAppend %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/progress-wizard.min.css' %}" />
    <script type="text/javascript" src='http://maps.google.com/maps/api/js?sensor=false&libraries=places'></script>
    <script type="text/javascript" src="{% static 'js/locationpicker.js' %}"></script>
    <script>
        $('#pickerMap').locationpicker({
            location: {latitude: {{ grievance.latitude }}, longitude: {{ grievance.longitude}} },
            radius: 50
        });
    </script>
{% endblock %}

src/core/templates/grievance/view.html
{% extends "layouts/default.html" %}
{% load staticfiles %}

{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">#{{grievance.issue_id}} {{grievance.title}}</h3>
        </div>
        <ul class="list-group">
            <li class="list-group-item">{{grievance.content}}</li>
        </ul>
        {% if grievance.geo_address %}
        <div class="panel-body">
            <div class="col-sm-3">
                <strong>Address:</strong><br>
                {% for addr in grievance.geo_address.0.address_components %}
                    {{ addr.long_name }}<br>
                {% endfor %}
            </div>
            <div class="col-sm-8">
                <div id="pickerMap" style="width: 800px; height: 300px;"></div>
            </div>
        </div>
        {% endif %}
        <ul class="list-group">
            <li class="list-group-item"><strong>Status:</strong><br>{{ grievance.status.status }}</li>
        </ul>
    </div>
{% endblock %}

{% block scriptsAppend %}
    <script type="text/javascript" src='http://maps.google.com/maps/api/js?sensor=false&libraries=places'></script>
    <script type="text/javascript" src="{% static 'js/locationpicker.js' %}"></script>
    <script>
        $('#pickerMap').locationpicker({
            location: {latitude: {{ grievance.latitude }}, longitude: {{ grievance.longitude}} },
            radius: 50
        });
    </script>
{% endblock %}