src/core/urls.py
from django.conf.urls import url, include

from . import views, grievance


urlpatterns = [
    url(r'^$', grievance.dashboard, name='dashboard_home'),
#     url(r'^register', views.register, name='register'),
    url(r'^grievance/add', grievance.add, name='add'),
    url(r'^grievance/all', grievance.allIssues, name='all'),
    url(r'^grievance/view/(?P<grievance_id>[0-9]+)', grievance.view, name='view'),
    url(r'^grievance/review/(?P<grievance_id>[0-9]+)', grievance.review, name='review'),
    url(r'^grievance/track/(?P<grievance_id>[0-9]+)', grievance.track, name='track'),
    url(r'^department/all', grievance.departments, name='dept_all'),
    url(r'^department/save', grievance.saveDepartment, name='dept_save'),
    url(r'^dashboard', grievance.dashboard, name='dashboard_main'),

]

src/pgs/urls.py
from django.conf.urls import include, url
from rest_framework import routers
from core  import grievance
from django.contrib import admin


router = routers.DefaultRouter()
router.register(r'^issues', grievance.IssueViewSet)

urlpatterns = [
    url(r'^', include('core.urls', namespace='core')),
    url(r'^', include('accounts.urls', namespace='accounts')),
    url(r'^api/', include(router.urls)),
    url(r'^auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^admin/', include(admin.site.urls)),
]

src/pgs/templates/layouts/default.html
{% load staticfiles %}
{% load accounts 	%}

<html lang="en">
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/theme/forms.css' %}" />
        <link rel="stylesheet" tyep="text/css" href="{% static 'css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/animate.min.css' %}" type="text/css">
        {% block stylesheets %}
        {% endblock %}

    </head>
    <body>
        <nav class="navbar navbar-default header" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/">Public Grievance System</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="{% url 'core:add' %}">New issue</a></li>
                        <li><a href="{% url 'core:all' %}">All issues</a></li>
                        <li><a href="{% url 'core:dept_all' %}">Departments</a></li>
                        <li><a href="{% url 'core:dashboard_main' %}">Dashboard</a></li>
                        {% loginstatus %}
                    </ul>
                </div>
            </div>
        </nav>

        <div class="container">
            <div class="row">
                {% block content %}
                {% endblock %}
            </div>
        </div>

        <hr>

        <div class="container">
            <div class="row">
                <hr>
                <footer>
                    <p>&copy;PGS </p>
                </footer>
            </div>
        </div> <!-- /container -->

        {% block scriptsPrepend %}
        {% endblock %}
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js" ></script>
        <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}" ></script>

        <!-- Plugin JavaScript -->
        <script src="/js/jquery.easing.min.js"></script>
        <script src="/js/jquery.fittext.js"></script>
        <script src="/js/wow.min.js"></script>
        {% block scriptsAppend %}
        {% endblock %}
    </body>
</html>