src/core/urls.py
from django.conf.urls import url, include

from . import views, grievance


urlpatterns = [
    url(r'^$', grievance.dashboard, name='dashboard_home'),
#     url(r'^register', views.register, name='register'),
    url(r'^grievance/add', grievance.add, name='add'),
    url(r'^grievance/all', grievance.allIssues, name='all'),
    url(r'^grievance/view/(?P<grievance_id>[0-9]+)', grievance.view, name='view'),
    url(r'^grievance/review/(?P<grievance_id>[0-9]+)', grievance.review, name='review'),
    url(r'^grievance/track/(?P<grievance_id>[0-9]+)', grievance.track, name='track'),
    url(r'^department/all', grievance.departments, name='dept_all'),
    url(r'^department/save', grievance.saveDepartment, name='dept_save'),
    url(r'^dashboard', grievance.dashboard, name='dashboard_main'),

]

src/pgs/urls.py
from django.conf.urls import include, url
from rest_framework import routers
from core  import grievance
from django.contrib import admin


router = routers.DefaultRouter()
router.register(r'^issues', grievance.IssueViewSet)

urlpatterns = [
    url(r'^', include('core.urls', namespace='core')),
    url(r'^', include('accounts.urls', namespace='accounts')),
    url(r'^api/', include(router.urls)),
    url(r'^auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^admin/', include(admin.site.urls)),
]

src/core/models.py
from django.db import models
from django.conf import settings
from jsonfield import JSONField


class Department(models.Model):
    dept_id = models.AutoField(primary_key=True)
    name    = models.CharField(max_length=40)
    description = models.CharField(max_length=255, blank=True)

    def __str__(self):
        return '[Name: ' + self.name + ', Description: ' + self.description +']'

class IssueStatus(models.Model):
    status = models.CharField(max_length=40)

class Issue(models.Model):

    class Meta:
        permissions = (
            ('review_issue', 'Can change the status of issue'),
        )

    issue_id    = models.AutoField(primary_key=True)
    status  = models.ForeignKey(IssueStatus)
    title   = models.CharField(max_length=256)
    content = models.TextField(max_length=1024)
    pic     = models.CharField(max_length=80, blank=True)
    latitude    = models.CharField(max_length=20, blank=True)
    longitude   = models.CharField(max_length=20, blank=True)
    geo_address     = JSONField(blank=True)
    twitter_handle  = models.CharField(max_length=20, blank=True)
    tweet   = JSONField(blank=True)
    category    = models.ForeignKey(Department, null=True)

    """
    TODO Make user compulsory - once user models are generated from tweets
    """
    user    = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True)

    def __str__(self):
        return '[Title: '+ self.title + ', Content: ' + self.content + ', User: ' + self.user.username + ']'

class Discussion(models.Model):
    issue   = models.ForeignKey(Issue)
    message = models.CharField(max_length=1024)

src/core/forms.py
from django import forms
from django.forms import ModelForm
from .models import Issue, Department


class GrievanceForm(ModelForm):
    #image   = forms.FileField()

    class Meta:
        model = Issue

        fields = ['title', 'content', 'latitude', 'longitude']
        widgets = {
            'latitude': forms.HiddenInput(attrs={'id': 'latitude'}),
            'longitude': forms.HiddenInput(attrs={'id': 'longitude'}),
        }
    def __init__(self, *args, **kwargs):
        super(GrievanceForm, self).__init__(*args, **kwargs)
        self.fields['latitude'].required = False
        self.fields['longitude'].required = False

class DepartmentForm(ModelForm):

    class Meta:
        model = Department

        fields = ['name', 'description']
        widgets = {
            'name': forms.TextInput(attrs={'id': 'dept_name'}),
            'description': forms.Textarea(attrs={'id': 'dept_description'})
        }

src/core/views.py
from django.shortcuts import render
from django.contrib.auth.models import User

import traceback

# def index(request):
#     all_roles = UserRole.objects.all()
#     role_options = []
#     for role in all_roles:
#         role_options.append({'id': role.id, 'role_name': role.role_name})
#     return render(request, 'core/index.html', {'role_options': role_options})
# 
# 
# 
# def register(request):
#     if request.method == 'POST':
#         form = RegistrationForm(request.POST)
#         if form.is_valid():
#             try:
#                 new_user = form.save(commit=False)
#                 new_user.save()
#             except Exception as e:
#                 context = {
#                         'alert_type': 'alert-danger',
#                         'content': 'Registration failed!! Unable to save.'
#                     }
#                 print(type(new_user).__name__)
#                 traceback.print_exc()
#                 return render(request, 'core/message.html', context)
#             context = {
#                     'alert_type': 'alert-success',
#                     'content': 'Registration successful!!'
#                 }
#             return render(request, 'core/message.html', context)
#     else:
#         form = RegistrationForm()
# 
#     return render(request, 'core/register.html', {'form': form})

# def register(request):
#     if request.method != 'POST':
#         context = {
#                     'alert_type': 'alert-danger',
#                     'content': 'Invalid request!!'
#                 }
#         return render(request, 'core/message.html', context)
#     user_name = request.POST['username']
#     user_password = request.POST['password']
#     user_re_password = request.POST['re-password']
#     user_role = request.POST['user_role']
#
#     if(user_password == user_re_password):
#         new_user = User(username = user_name, password = user_password)
#         try:
#             new_user.save()
#             print('New_user: '+ str(new_user))
#             role_obj = UserRole.objects.filter(id=user_role).get()
#             print('User role: ' + type(role_obj).__name__)
#             profile = UserProfile(user = new_user, role = role_obj)
#             profile.save()
#         except Exception as e:
#             print(e)
#             new_user.delete()
#             context = {
#                         'alert_type': 'alert-danger',
#                         'content': 'Registration failed!!'
#                     }
#             return render(request, 'core/message.html', context)
#
#         context = {
#                     'alert_type': 'alert-success',
#                     'content': 'Registration successful!!'
#                 }
#         return render(request, 'core/message.html', context)
#
#     context = {
#                 'alert_type': 'alert-warning',
#                 'content': 'Registration failed!! Passwords did not match.'
#             }
#     return render(request, 'core/message.html', context)

src/core/templates/department/all.html
{% extends "layouts/default.html" %}
{% load staticfiles %}

{% block content %}
	<div class="container">
	    <div class="row">
    	{% for dept, stats in departments %}
    
		    <div class="col-md-4 col-sm-6 col-xs-12">
		        <div class="panel panel-info">
		            <div class="panel-heading">
		                <h3 class="panel-title">{{ dept.name }}</h3>
		            </div>
		            <div class="panel-body">
		                {{ dept.description }}
		            </div>
		            <table class="table table-hover">
		                <tbody>
		                    <tr>
		                        <td><strong>Total issues:</strong></td>
		                        <td><strong>{{ stats.total }}</strong></td>
		                    </tr>
		                    <tr>
		                        <td>Issues resolved:</td>
		                        <td>{{ stats.resolved }}</td>
		                    </tr>
		                    <tr>
		                        <td>Still to be resolved:</td>
		                        <td>{{ stats.un_resolved }}</td>
		                    </tr>
		                </tbody>
		            </table>
		        </div>
		    </div>
	    {% empty %}
	    
	    <div class="alert alert-info">
	    No departments to show
	    </div>
	    
	    {% endfor 	%}
	    </div>
    </div>
    {% if dept_form %}
    <div class="container">
	    <div class="row">
	        <div class="col-sm-6 col-xs-12">
	            <div class="panel panel-default">
	                <div class="panel-heading">
	                    <h3 class="panel-title">Add new department</h3>
	                </div>
	                <div class="panel-body">
	                    <form class="form" action="{% url 'core:dept_save' %}" method="POST">
	                        {% csrf_token %}
	                        {{ dept_form.non_field_errors }}
	                        <div class="form-group">
	                            {{ dept_form.name.errors }}
	                            <label for="{{ dept_form.name.id_for_label }}">Name:</label>
	                            {{ dept_form.name }}
	                        </div>
	                        <div class="form-group">
	                            {{ dept_form.description.errors }}
	                            <label for="{{ dept_form.description.id_for_label }}">Description:</label>
	                            {{ dept_form.description }}
	                        </div>
	                        <div class="form-group">
	                            <button class="btn btn-primary">Save</button>
	                        </div>
	                    </form>
	                </div>
	            </div>
	        </div>
	    </div>
    </div>
   	{% endif %}
{% endblock %}