src/accounts/urls.py
from django.conf.urls import url, include
from accounts import views

urlpatterns = [
    url(r'^register/', views.userregister, name='userregistration'),
    url(r'^login/', views.userlogin, name='userlogin'),
    url(r'^logout/', views.userlogout, name='logout'),
]

src/pgs/urls.py
from django.conf.urls import include, url
from rest_framework import routers
from core  import grievance
from django.contrib import admin


router = routers.DefaultRouter()
router.register(r'^issues', grievance.IssueViewSet)

urlpatterns = [
    url(r'^', include('core.urls', namespace='core')),
    url(r'^', include('accounts.urls', namespace='accounts')),
    url(r'^api/', include(router.urls)),
    url(r'^auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^admin/', include(admin.site.urls)),
]

src/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager


class UserRole(models.Model):
    roleid  = models.AutoField(primary_key=True)
    rolename   = models.CharField(max_length=50)

    def __str__(self):
        return self.rolename


class UserManager(BaseUserManager):
    def create_user(self, username, password=None):
        """
        Creates and saves a User with given username
        and password.
        """
        if not username:
            raise ValueError('User must have a valid username')
        user = self.model( username = username,)

        user.set_password(password)
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    userid  = models.AutoField(primary_key=True)
    username    = models.CharField(max_length=40, unique=True)
    role    = models.ForeignKey(UserRole)

    objects = UserManager()

    USERNAME_FIELD = 'username'


    def get_full_name(self):
        return self.username

    def get_short_name(self):
        return self.username

src/accounts/forms.py
from django import forms
from django.forms import ModelForm
from .models import User
from django.forms.forms import Form


class RegistrationForm(ModelForm):
    repassword = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username', 'password']

        widgets = {
            'password': forms.PasswordInput(),
        }

    def clean(self):
        cleaned_data = super(RegistrationForm, self).clean()
        password = cleaned_data.get("password")
        re_password = cleaned_data.get("repassword")
        
        if not (password and re_password):
            raise forms.ValidationError('Password fields cannot be empty')

        if re_password != password:
            raise forms.ValidationError(
                "Passwords did not match."
            )
        
        return cleaned_data
    
    def cleanedPassword(self):
        cleaned_data = self.clean()
        password = cleaned_data.get("password")
        return password
            
    def save(self, commit=True):
        user    = super(RegistrationForm, self).save(commit=False)
        user.set_password(self.cleanedPassword())
        if commit:
            user.save()
            
        return user

class LoginForm(Form):
    username    = forms.CharField(max_length=40)
    password    = forms.CharField(widget=forms.PasswordInput)

src/accounts/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.http.response import HttpResponseRedirect

from .models import User, UserRole
from .forms import RegistrationForm, LoginForm
import logging
from traceback import print_exc


logger = logging.getLogger(__name__)

def userregister(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)

        if form.is_valid():
            print('Form is valid')
            newuser = form.save(commit=False)
            newuser.role    = UserRole.objects.filter(roleid=3).get()

            try:
                newuser.save()
                context = {
                        'alert_type': 'alert-success',
                        'content': 'User registered successfully!!'
                    }
                return render(request, 'core/message.html', context)
            
            except Exception as e:
                logger.error(e)
                print_exc()
                context = {
                        'alert_type': 'alert-danger',
                        'content': 'Failed to register!!'
                    }
                return render(request, 'core/message.html', context)
    else:
        form = RegistrationForm()
        
    return render(request, 'accounts/signup.html', {'form' : form})


def userlogin(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            user_name = request.POST['username']
            user_password = request.POST['password']
            print('Username: ' + user_name + ', Password: ' + user_password)
            user = authenticate(username= user_name, password = user_password)
        
            if user:
                if user.is_active:
                    login(request, user)
                    #request.session.set_expiry(60)
                    return HttpResponseRedirect('/')
            else:
                context = {
                        'alert_type': 'alert-danger',
                        'content': 'Invalid request!!'
                    }
                return render(request, 'core/message.html', context)
    else:
        form = LoginForm()
        
    return render(request, 'accounts/login.html', {'form' : form})

def userlogout(request):
    logout(request)
    return HttpResponseRedirect('/')
    

src/accounts/templates/accounts/accountbuttons.html
<a class="btn btn-primary navbar-btn" href="{% url 'accounts:userlogin' %}" role="button">Login</a>
<a class="btn btn-success navbar-btn" href="{% url 'accounts:userregistration' %}" role="button">Register</a>

src/accounts/templates/accounts/login.html
{% extends "layouts/default.html" %}

{% block content %}
	<div >
        <form action="" method="POST" >
            <fieldset>
                <legend>Login</legend>
                {% csrf_token %}
                {{ form.non_field_errors }}
                <div class="form-group">
                    {{ form.username.errors }}
                    <label for="{{ form.username.id_for_label }}">Username:</label>
                    {{ form.username }}
                </div>
                <div class="form-group">
                    {{ form.password.errors }}
                    <label for="{{ form.password.id_for_label }}">Password:</label>
                    {{ form.password }}
                </div>
                <input class="btn btn-primary" type="submit" value="Signin" />
            </fieldset>
        </form>
    </div>
{% endblock %}

src/accounts/templates/accounts/signup.html
{% extends "layouts/default.html" %}

{% block content %}
	<div >
        <form action="" method="POST" >
            <fieldset>
                <legend>Register</legend>
                {% csrf_token %}
                {{ form.non_field_errors }}
                <div class="form-group">
                    {{ form.username.errors }}
                    <label for="{{ form.username.id_for_label }}">Username:</label>
                    {{ form.username }}
                </div>
                <div class="form-group">
                    {{ form.password.errors }}
                    <label for="{{ form.password.id_for_label }}">Password:</label>
                    {{ form.password }}
                </div>
                <div class="form-group">
                    {{ form.repassword.errors }}
                    <label for="{{ form.repassword.id_for_label }}">Re-enter Password:</label>
                    {{ form.repassword }}
                </div>
                <input class="btn btn-primary" type="submit" value="Sign Up" />
            </fieldset>
        </form>
    </div>
{% endblock %}

src/accounts/templates/accounts/userbutton.html
<li class="dropdown">
	<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
		<span class="glyphicon glyphicon-user"></span>
	</a>
	<ul class="dropdown-menu">
		<li><a>{{ user.username }} ({{ user.role.rolename }})</a></li>
		<li role="seperator" class="divider"></li>
		<li><a href="{% url 'accounts:logout' %}">Logout</a>
	</ul>
<li>